### ISSUE TITLE
Carthage build and name issues

### ISSUE THREAD

**Issue by jPaolantonio** [perflabs/PerfSDK#3]
When using this library with Carthage, I ran into 2 issues:

1) When building with `--platform ios`, I can getting a `Dependency "ios-lib" has no shared framework schemes for any of the platforms: iOS` error.

2) The library / framework name seems to be `ios-lib`. This name should be more descriptive.

**Comment by jgrana** [comment]
@jPaolantonio renamed the repo to PerfSDK to be more descriptive and shared the framework scheme.
